services:
  - type: web
    name: ishema-bot-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "python start.py"
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PINECONE_URL
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: INDEX_NAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
